package xpress;

//Java code generated by the Xpress-IVE deployment wizard

import java.io.*;
import com.dashoptimization.*;

public class RunModel
{
 public static void main(String[] args)
 {
  int result;

  try {
   result=runMoselModel();
   System.out.println("Model execution returned: "+result);
  }
  catch(XPRMLicenseError e)
  {
   System.out.println("Failed to licence Mosel : " + e.getMessage());
  }
  catch(java.lang.Exception e)
  {
   System.out.println("Model loading or execution error : " + e.getMessage());
  }
 }

 static int runMoselModel() throws XPRMLicenseError, IOException
 {
  XPRMModel model;
  XPRM xprm;
  int result;

  // Initialize Mosel
  xprm = new XPRM();

  // Load compiled model (.BIM file)
  model=xprm.loadModel("d:\\units-magistrale\\tecniche e modelli di ottimizzazione b\\xpress project\\xdefranceschi\\aguiaristancich\\20110531 - pathanalisys.bim");

  // Run model
  model.run();

  if(model.getExecStatus() != XPRMModel.RT_OK)
  {
    throw new java.lang.RuntimeException("Error during execution");
  }
  else
  {
      result=model.getResult();
      return result;
  }

  // Clean up is automatic in Java
 }
}
